#!/bin/bash
set -e

HERMES_DIR="$HOME/.hermes"
ENV_FILE="$HERMES_DIR/.env"

# Determine if we need sudo (directory owned by container user)
if [ -d "$HERMES_DIR" ] && [ ! -w "$HERMES_DIR" ]; then
    SUDO="sudo"
    sudo -v  # cache password upfront
else
    SUDO=""
fi

$SUDO mkdir -p "$HERMES_DIR"

# --- Check existing .env ---
action="create"
if $SUDO [ -f "$ENV_FILE" ]; then
    content=$($SUDO grep -vE '^\s*(#|$)' "$ENV_FILE" || true)
    if [ -n "$content" ]; then
        echo "Existing $ENV_FILE found with keys configured."
        echo "1) Modify  (edit in-place, preserving existing keys)"
        echo "2) Recreate (start fresh)"
        echo "3) Skip"
        read -rp "Choose [1-3]: " choice
        case "$choice" in
            1) action="modify" ;;
            2) action="recreate" ;;
            *) echo "Skipping."; exit 0 ;;
        esac
    fi
fi

# --- Prompt helper ---
prompt_key() {
    local var="$1"
    local label="$2"
    local default="$3"
    local current=""
    if [ "$action" = "modify" ] && $SUDO [ -s "$ENV_FILE" ] 2>/dev/null; then
        current=$($SUDO grep "^${var}=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)
    fi
    if [ -n "$current" ]; then
        echo "[existing] $var=$current"
        read -rp "  Override? (leave empty to keep): " val
        if [ -n "$val" ]; then
            echo "${var}=${val}"
        else
            echo "${var}=${current}"
        fi
    else
        local prompt_str="$label"
        [ -n "$default" ] && prompt_str+=" [$default]"
        read -rp "$prompt_str: " val
        val="${val:-$default}"
        if [ -n "$val" ]; then
            echo "${var}=${val}"
        fi
    fi
}

# --- Build new env content ---
build_env() {
    cat <<'EOF'
# Hermes Agent Environment Configuration
# Generated by hermes-init

EOF
    prompt_key "ANTHROPIC_API_KEY" "Anthropic API key (Claude)"
    prompt_key "OPENAI_API_KEY" "OpenAI API key"
    prompt_key "OPENROUTER_API_KEY" "OpenRouter API key"
    prompt_key "OPENCODE_ZEN_API_KEY" "OpenCode Zen API key"
    prompt_key "ABACUSAI_API_KEY" "AbacusAI API key"
    prompt_key "GOOGLE_API_KEY" "Google AI Studio / Gemini API key"
    prompt_key "GITHUB_TOKEN" "GitHub personal access token"
    echo ""
    echo "# --- Messaging ---"
    prompt_key "TELEGRAM_BOT_TOKEN" "Telegram Bot token (from @BotFather)"
    prompt_key "TELEGRAM_ALLOWED_USERS" "Telegram allowed user IDs (comma-separated)"
    prompt_key "SLACK_BOT_TOKEN" "Slack Bot token"
    prompt_key "DISCORD_BOT_TOKEN" "Discord Bot token"
    echo ""
    echo "# --- Tools ---"
    prompt_key "EXA_API_KEY" "Exa API key (web search)"
    prompt_key "FIRECRAWL_API_KEY" "Firecrawl API key (web crawl)"
    prompt_key "BROWSERBASE_API_KEY" "Browserbase API key (browser automation)"
    prompt_key "BROWSERBASE_PROJECT_ID" "Browserbase Project ID"
    prompt_key "PLAYWRIGHT_WS_ENDPOINT" "Playwright server WebSocket URL" "ws://hermes-playwright:3000"
    prompt_key "FAL_KEY" "FAL.ai API key (image generation)"
    echo ""
    echo "# --- Gateway ---"
    local gw_mode
    read -rp "Allow all users (gateway open access)? [y/N]: " gw_mode
    if [[ "$gw_mode" =~ ^[yY] ]]; then
        echo "GATEWAY_ALLOW_ALL_USERS=true"
    fi
}

tmp=$(mktemp)
build_env > "$tmp"
$SUDO cp "$tmp" "$ENV_FILE"
rm "$tmp"
echo "Written $ENV_FILE"
